const trailsRenderer = {
  type: "unique-value",
  field: "STATUS",
  uniqueValueInfos: [
    {
      value: "OPEN",
      symbol: {
        type: "cim",
        data: {
          type: "CIMSymbolReference",
          symbol: {
            type: "CIMLineSymbol",
            symbolLayers: [
              {
                type: "CIMSolidStroke",
                enable: true,
                capStype: "Round",
                joinStyle: "Round",
                width: 2.5,
                color: [214, 45, 65, 255],
              },
              {
                type: "CIMSolidStroke",
                enable: true,
                capStype: "Round",
                joinStyle: "Round",
                width: 6,
                color: [255, 255, 255, 255],
              },
            ],
          },
        },
      },
    },
    {
      value: "CLSD",
      symbol: {
        type: "cim",
        data: {
          type: "CIMSymbolReference",
          symbol: {
            type: "CIMLineSymbol",
            symbolLayers: [
              {
                type: "CIMSolidStroke",
                effects: [
                  {
                    type: "CIMGeometricEffectDashes",
                    dashTemplate: [10, 4, 10, 4],
                    lineDashEnding: "NoConstraint",
                    controlPointEnding: "NoConstraint",
                  },
                ],
                enable: true,
                capStype: "Round",
                joinStyle: "Round",
                width: 1.8,
                color: [214, 45, 65, 255],
              },
              {
                type: "CIMSolidStroke",
                effects: [
                  {
                    type: "CIMGeometricEffectDashes",
                    dashTemplate: [10, 4, 10, 4],
                    lineDashEnding: "NoConstraint",
                    controlPointEnding: "NoConstraint",
                  },
                ],
                enable: true,
                capStype: "Round",
                joinStyle: "Round",
                width: 4,
                color: [255, 255, 255, 255],
              },
              {
                type: "CIMVectorMarker",
                enable: true,
                anchorPointUnits: "Relative",
                dominantSizeAxis3D: "Y",
                size: 15,
                billboardMode3D: "FaceNearPlane",
                frame: {
                  xmin: 0,
                  ymin: 0,
                  xmax: 510,
                  ymax: 510,
                },
                markerPlacement: {
                  type: "CIMMarkerPlacementAlongLineSameSize",
                  endings: "Custom", // "WithMarkers",
                  placementTemplate: [100], // determines space between each marker
                  angleToLine: false,
                },
                markerGraphics: [
                  {
                    type: "CIMMarkerGraphic",
                    geometry: {
                      rings: [
                        [
                          [128, 280],
                          [382, 280],
                          [382, 230],
                          [128, 230],
                          [128, 280],
                        ],
                        [
                          [255, 0],
                          [305, 5],
                          [352, 19],
                          [396, 43],
                          [435, 75],
                          [467, 114],
                          [491, 158],
                          [505, 205],
                          [510, 255],
                          [505, 305],
                          [491, 352],
                          [467, 396],
                          [435, 435],
                          [396, 467],
                          [352, 491],
                          [305, 505],
                          [255, 510],
                          [205, 505],
                          [158, 491],
                          [114, 467],
                          [75, 435],
                          [43, 396],
                          [19, 352],
                          [5, 305],
                          [0, 255],
                          [5, 205],
                          [19, 158],
                          [43, 114],
                          [75, 75],
                          [114, 43],
                          [158, 19],
                          [205, 5],
                          [255, 0],
                        ],
                      ],
                    },
                    symbol: {
                      type: "CIMPolygonSymbol",
                      symbolLayers: [
                        {
                          type: "CIMSolidFill",
                          enable: true,
                          color: [214, 45, 65, 255],
                        },
                      ],
                    },
                  },
                ],
                scaleSymbolsProportionally: true,
                respectFrame: true,
                clippingPath: {
                  type: "CIMClippingPath",
                  clippingType: "Intersect",
                  path: {
                    rings: [
                      [
                        [0, 0],
                        [510, 0],
                        [510, 510],
                        [0, 510],
                        [0, 0],
                      ],
                    ],
                  },
                },
              },
            ],
          },
        },
      },
    },
  ],
};

const hutsRenderer = {
  type: "simple",
  symbol: {
    type: "cim",
    data: {
      type: "CIMSymbolReference",
      symbol: {
        type: "CIMPointSymbol",
        symbolLayers: [
          {
            type: "CIMVectorMarker",
            enable: true,
            anchorPointUnits: "Relative",
            dominantSizeAxis3D: "Y",
            size: 40,
            billboardMode3D: "FaceNearPlane",
            frame: {
              xmin: 0,
              ymin: 0,
              xmax: 21,
              ymax: 21,
            },
            markerGraphics: [
              {
                type: "CIMMarkerGraphic",
                geometry: {
                  rings: [
                    [
                      [6.53, 12.83],
                      [6.88, 10.69],
                      [8.19, 10.97],
                      [9.1, 13.71],
                      [6.53, 12.83],
                    ],
                    [
                      [6.02, 8.57],
                      [5.45, 7.6],
                      [5.26, 6.5],
                      [5.32, 5.87],
                      [5.51, 5.26],
                      [5.81, 4.7],
                      [6.21, 4.2],
                      [6.71, 3.8],
                      [7.27, 3.5],
                      [7.88, 3.31],
                      [8.51, 3.25],
                      [9.14, 3.31],
                      [9.75, 3.5],
                      [10.31, 3.8],
                      [10.81, 4.2],
                      [11.21, 4.69],
                      [11.51, 5.26],
                      [11.7, 5.87],
                      [11.76, 6.5],
                      [11.7, 7.14],
                      [11.51, 7.75],
                      [11.21, 8.31],
                      [10.81, 8.8],
                      [10.32, 9.2],
                      [9.76, 9.5],
                      [9.15, 9.69],
                      [8.51, 9.75],
                      [7.79, 9.66],
                      [7.08, 9.41],
                      [7.22, 8.61],
                      [7.13, 8.24],
                      [6.8, 8.04],
                      [6.62, 8.01],
                      [6.25, 8.09],
                      [6.05, 8.42],
                      [6.02, 8.57],
                    ],
                    [
                      [16.02, 10.09],
                      [15, 4.62],
                      [14.79, 4.28],
                      [14.47, 4.22],
                      [14.29, 4.27],
                      [14.03, 4.51],
                      [14, 4.92],
                      [15, 10],
                      [11.3, 10],
                      [12.02, 9.29],
                      [12.56, 8.44],
                      [12.89, 7.49],
                      [13, 6.5],
                      [12.91, 5.62],
                      [12.66, 4.78],
                      [12.24, 4],
                      [11.68, 3.32],
                      [11, 2.76],
                      [10.22, 2.34],
                      [9.38, 2.09],
                      [8.5, 2],
                      [7.62, 2.09],
                      [6.78, 2.34],
                      [6, 2.76],
                      [5.32, 3.32],
                      [4.76, 4],
                      [4.34, 4.78],
                      [4.09, 5.62],
                      [4, 6.5],
                      [4.12, 7.52],
                      [4.46, 8.48],
                      [5.03, 9.35],
                      [5.78, 10.07],
                      [5.26, 13.22],
                      [5.39, 13.58],
                      [5.72, 13.8],
                      [9.84, 15.16],
                      [10.11, 15.14],
                      [11.62, 14.78],
                      [11.95, 14.46],
                      [11.96, 14],
                      [11, 11],
                      [15.58, 11],
                      [15.91, 10.87],
                      [16.07, 10.55],
                      [16.02, 10.09],
                    ],
                    [
                      [10.49, 17],
                      [10.6, 17.57],
                      [10.93, 18.06],
                      [11.42, 18.39],
                      [11.99, 18.5],
                      [12.56, 18.39],
                      [13.05, 18.06],
                      [13.38, 17.57],
                      [13.49, 17],
                      [13.38, 16.43],
                      [13.05, 15.94],
                      [12.56, 15.61],
                      [11.99, 15.5],
                      [11.42, 15.61],
                      [10.93, 15.94],
                      [10.6, 16.43],
                      [10.49, 17],
                    ],
                  ],
                },
                symbol: {
                  type: "CIMPolygonSymbol",
                  symbolLayers: [
                    {
                      type: "CIMSolidStroke",
                      enable: true,
                      capStyle: "Round",
                      joinStyle: "Round",
                      lineStyle3D: "Strip",
                      miterLimit: 10,
                      width: 0,
                      color: [0, 0, 0, 255],
                    },
                    {
                      type: "CIMSolidFill",
                      enable: true,
                      color: [51, 51, 51, 255],
                    },
                  ],
                },
              },
            ],
            scaleSymbolsProportionally: true,
            respectFrame: true,
          },
        ],
      },
    },
  },
};
